### ISSUE TITLE
Docker localhost Erkennung

### ISSUE THREAD

**Issue by ChaudhryAhmed** [bela127/MicroServiceWebShop#17]
application.yaml
insbesondere security basic enabled auf "false" setzen:
```
server:
  port: 8084
spring:
  application:
    name: category-service
security:
  basic:
    enabled: false
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"
```

Vielleicht noch das:
Eureka yml :server:
  ```
port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
```
