### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by ChaudhryAhmed** [bela127/MicroServiceWebShop#18]
Beispiel yaml-config:
```
version: '2'
services:
  eureka-server:
    build: ./eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    tty: false
    ports:
      - '8761:8761'
  category-service:
    build: ./category-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    tty: false
    ports:
      - '8084:8084'
  product-service:
    build: ./product-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    tty: false
    ports:
      - '8082:8082'
  user-service:
    build: ./user-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    tty: false
    ports:
      - '8083:8083'
  user-management-service:
    build: ./user-management-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    tty: false
    ports:
      - '8090:8090'
  catalog-management-service:
    build: ./catalog-management-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
      oauth2.resource.userInfoUri: http://auth-server:8099/api/clientinfo
    tty: false
    ports:
      - '8091:8091'
  auth-server:
    build: ./auth-server
    tty: false
    ports:
      - '8099:8099'
    environment:
      - userService=http://user-service:8083/
  frontend:
    build: ./frontend
    tty: false
    ports:
      - '4200:4200'
    environment:
       zuulServer: http://zuul-server:8081/
       authServer: http://auth-server:8099/

  zuul-server:
    build: ./zuul-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
      oauth2.client.access-token-uri: http://auth-server:8099/oauth/token
      oauth2.client.user-authorization-uri: http://auth-server:8099/dialog/authorize 
      oauth2.resource.userInfoUri: http://auth-server:8099/api/clientinfo
    tty: false
    ports:
      - '8081:8081'
```
